# Generated by Django 5.0.8 on 2026-02-13 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idp_user", "0007_user_demo"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="UserRole",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS idp_user_userrole;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
